### PR TITLE
community: formatting

### PR DESCRIPTION
**Pull request by edk0**
also use (more) correct URL for freenode

### CODE REVIEW

**Comment by hreeder** [comment]
After previewing locally, the only real things I can say are about the dashes, they feel a bit too long.

If nothing else, they should have spaces either side of them.

**Comment by AbstractBeliefs** [comment]
@hreeder are you fundamentally OK with this PR?

**Comment by hreeder** [comment]
Given a significant portion of this is formatting changes, I would like to
address this before merging rather than rushing to merge in the whole PR
just for the content.

**Comment by edk0** [comment]
I believe I'm using em dashes [correctly](https://en.wikipedia.org/wiki/Dash#Modes_of_use_2). If you have a particular style guide in mind, maybe you should link to it in the repo somewhere.

**Comment by hreeder** [comment]
Fair enough. I've taken the change then and applied it site wide to make things consistent.

**Pull request merged**
